- name: create ansuser
  tags: always
  user:
    name: ansuser
    groups: root

- name: add ssh key for ansuser
  authorized_key:
    user: ansuser
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPzD0eH8qfJL6JayUN/EcDGn1rtPQA5nIp9tAyT3Fk7f ansuser"

- name: add sudoers file for ansuser
  tags: always
  copy:
    src: sudoer_ansuser
    dest: /etc/sudoers.d/ansuser
    owner: root
    group: root
    mode: 0440
